### ISSUE TITLE
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection

### ISSUE THREAD

**Issue by isidentical** [ApolloTVofficial/Claws#10]
When i try to send a request with python i get this warning;
```js
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Illegal arguments: string, undefined
    at e (/srv/apollo/Claws/public/bcrypt.js:31:332)
    at Object.m.compare (/srv/apollo/Claws/public/bcrypt.js:32:53)
    at Promise (/srv/apollo/Claws/src/api/authRoutes.js:53:20)
    at new Promise (<anonymous>)
    at authRoutes.post (/srv/apollo/Claws/src/api/authRoutes.js:52:32)
    at Layer.handle [as handle_request] (/srv/apollo/Claws/node_modules/express/lib/router/layer.js:95:5)
    at next (/srv/apollo/Claws/node_modules/express/lib/router/route.js:137:13)
    at rateLimit (/srv/apollo/Claws/src/api/authRoutes.js:32:9)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by claws-dev** [comment]
What is the request?
